<a href="https://colab.research.google.com/github/kibuba-njihia/the-snake/blob/main/Practice_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Enumerate Function**
This is used in giving consecutive values to your iterables

In [1]:
for i,j in enumerate(['a','b','c']):
  print(i,j)
  print(type(j))


for i in enumerate([40,45,50]):
  print(i)
  print(type(i))

0 a
<class 'str'>
1 b
<class 'str'>
2 c
<class 'str'>
(0, 40)
<class 'tuple'>
(1, 45)
<class 'tuple'>
(2, 50)
<class 'tuple'>

In [2]:
import numpy as np

fahrenheit_a = np.array([-40,  14, 32, 46, 59, 72, 100],  dtype=float)
print(fahrenheit_a[-1])

100.0

# **Pandas**

In [3]:
import pandas as pd

In [4]:
#Creating a series - sort of a column in a table
data = ['a','b',' c']

my_series = pd.Series(data)
print(my_series)
print(type(my_series))
print(my_series[0])

0     a
1     b
2     c
dtype: object
<class 'pandas.core.series.Series'>
a

In [5]:
#Creating your own labels - alternatives for the default 0,1,2,....
#Done using the index ftn
data = ['a','b',' c']

my_series = pd.Series(data,index = ['first','second','third'])
print(my_series)
print(type(my_series))
print(my_series['first'])

first      a
second     b
third      c
dtype: object
<class 'pandas.core.series.Series'>
a

From series, we now move on to the real stuff: Dataframes

In [6]:
#Loading Dataframes
data = [['Trevor',27],['Julie',26],['Sijui',1]]
df = pd.DataFrame(data ,columns=['Name','Age'])
print(df)
print(type(df))

     Name  Age
0  Trevor   27
1   Julie   26
2   Sijui    1
<class 'pandas.core.frame.DataFrame'>

In [7]:
#Locating specific rows
print(df.loc[[0,2]])

     Name  Age
0  Trevor   27
2   Sijui    1

**Cleaning empy/null cells**

In [8]:
# prompt: create a dataframe with 2 columns and 10 rows

import pandas as pd
import numpy as np

# Create a DataFrame with 2 columns and 10 rows
data = {'col1': np.random.rand(10), 'col2': np.random.randint(0, 100, 10)}
df = pd.DataFrame(data)

df

       col1  col2
0  0.461909    68
1  0.455079    98
2  0.948702    71
3  0.159069    59
4  0.344246    25
5  0.001318    38
6  0.441830    76
7  0.222594     7
8  0.880606    58
9  0.788746    81

In [9]:
# prompt: randomly select 5 items from a list

import random

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random_items = random.sample(my_list, 5)
random_items

[4, 1, 6, 10, 7]

**Pop**

In [10]:
import pandas as pd
import numpy as np

In [11]:


df = pd.DataFrame([('falcon', 'bird', 389.0),
                    ('parrot', 'bird', 24.0),
                    ('lion', 'mammal', 80.5),
                    ('monkey', 'mammal', np.nan)],
                   columns=('name', 'class', 'max_speed'))
df

     name   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [12]:
popped_df = df.pop('class')

In [13]:
popped_df

0      bird
1      bird
2    mammal
3    mammal
Name: class, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      object
 1   max_speed  3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 196.0+ bytes

In [15]:
# will get back in the evening

In [16]:
# consistency is key but we shall overcome

In [17]:
# Let's do this again on valentines

In [18]:
#Started at BM, Let's get back to this

In [19]:
# 8 months into BM, NEW YEAR let's switch back to the other python file

In [20]:
# 1 year into BM, Let's see what the other file has